MESATestHub/config/routes.rb
Rails.application.routes.draw do
  get 'sessions/new'

  resources :users do
    resources :computers
  end
  resources :sessions
  resources :computers
  resources :test_cases do
    resources :test_instances
  end

  root to: 'test_cases#index' # , params: { version: 'latest' }

  # meant for remote HTTP requests
  post '/test_instances/submit', to: 'test_instances#submit'

  get 'admin', to: 'users#admin', as: 'admin'
  get 'admin_edit_user', to: 'users#admin_edit_user', as: 'admin_edit_user'
  delete 'admin_destroy_user', to: 'users#admin_destroy_user',
                               as: 'admin_delete_user'

  get 'signup', to: 'users#new', as: 'signup'
  get 'login', to: 'sessions#new', as: 'login'
  get 'logout', to: 'sessions#destroy', as: 'logout'

  post 'check_user', to: 'sessions#check_credentials', as: 'check_user'
  post 'check_computer', to: 'computers#check_computer', as: 'check_computer'

  # index of a particular user's computers's test instances
  get 'user/:user_id/computers/:id/test_instances',
      to: 'computers#test_instances_index',
      as: 'user_computer_test_instances'

  # global list of all computers (admins only)
  get 'all_computers', to: 'computers#index_all', as: 'all_computers'
end

MESATestHub/app/controllers/test_cases_controller.rb
class TestCasesController < ApplicationController
  before_action :set_test_case, only: %i[show edit update destroy]

  before_action :authorize_admin, only: %i[edit update destroy new create]

  # GET /test_cases
  # GET /test_cases.json
  def index
    @mesa_versions = TestCase.versions
    @selected = params[:version] || 'latest'
    # big daddy query, hopefully optimized
    @version_number = case @selected
                      when 'all' then :all
                      when 'latest' then @mesa_versions.max
                      else
                        @selected.to_i
                      end
    @test_cases = TestCase.find_by_version(@version_number)
    @header_text = case @selected
                   when 'all' then 'Last Results for All Tests'
                   else
                     "Test Cases Tested on Version #{@version_number}"
                   end
    @specs = TestCase.version_computer_specs(@test_cases, @version_number)
    @statistics = TestCase.version_statistics(@test_cases, @version_number)
    @version_status =
      if @statistics[:mixed] > 0
        :mixed
      elsif @statistics[:failing] > 0
        if @statistics[:passing] > 0
          :mixed
        else
          :failing
        end
      elsif @statistics[:passing] > 0
        :passing
      else
        :untested
      end

    @status_text = case @version_status
                   when :passing then 'All tests passing on all computers.'
                   when :mixed
                     'Some tests fail on at least some computers.'
                   when :failing then 'All tests fail with all computers.'
                   else
                     'No tests have been run for this version.'
                   end

    @status_class = case @version_status
                    when :passing then 'text-success'
                    when :mixed then 'text-warning'
                    when :failing then 'text-danger'
                    else
                      'text-info'
                    end

    # for populating version select menu
    @mesa_versions.prepend('all')
    @mesa_versions.prepend('latest')

    # set up colored table rows depending on passage status
    @computer_counts = {}
    @last_versions = {}
    @row_classes = {}
    @last_tested = {}
    @test_cases.each do |t|
      if @selected == 'all'
        @last_versions[t] = t.last_version
      else
        @computer_counts[t] = t.version_computers_count(@version_number)
      end
      @last_tested[t] = t.last_tested
      @row_classes[t] =
        case t.version_status(@version_number)
        when 0 then 'table-success'
        when 1 then 'table-danger'
        else
          'table-warning'
        end
    end
  end

  # GET /test_cases/1
  # GET /test_cases/1.json
  def show
    @selected = params[:version] || 'latest'
    @selected = 'latest' if @selected == 'all'
    # big daddy query, hopefully optimized
    @mesa_versions = @test_case.mesa_versions
    @version_number = if @selected == 'latest'
                        @mesa_versions.max
                      else
                        @selected.to_i
                      end
    # all test instances, sorted by upload date
    @test_instances = @test_case.version_instances(@version_number)
    @test_instance_classes = {}
    @test_instances.each do |instance|
      @test_instance_classes[instance] =
        if instance.passed
          'table-success'
        else
          'table-danger'
        end
    end

    # text and class for last version test status
    @version_status, @version_class = passing_status_and_class(
      @test_case.version_status(@version_number)
    )

    # for populating select list
    @mesa_versions.prepend('latest')
  end

  # GET /test_cases/new
  def new
    @test_case = TestCase.new
    @modules = TestCase.modules
  end

  # GET /test_cases/1/edit
  def edit
    @modules = TestCase.modules
    @show_path = test_case_path(@test_case)
  end

  # POST /test_cases
  # POST /test_cases.json
  def create
    @test_case = TestCase.new(test_case_params)

    respond_to do |format|
      if @test_case.save
        format.html do
          redirect_to @test_case, notice: 'Test case was successfully created.'
        end
        format.json { render :show, status: :created, location: @test_case }
      else
        format.html { render :new }
        format.json do
          render json: @test_case.errors, status: :unprocessable_entity
        end
      end
    end
  end

  # PATCH/PUT /test_cases/1
  # PATCH/PUT /test_cases/1.json
  def update
    respond_to do |format|
      if @test_case.update(test_case_params)
        format.html { redirect_to @test_case, notice: 'Test case was successfully updated.' }
        format.json { render :show, status: :ok, location: @test_case }
      else
        format.html { render :edit }
        format.json { render json: @test_case.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /test_cases/1
  # DELETE /test_cases/1.json
  def destroy
    @test_case.destroy
    respond_to do |format|
      format.html { redirect_to test_cases_url, notice: 'Test case was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_test_case
      @test_case = TestCase.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def test_case_params
      params.require(:test_case).permit(:name, :module, :version_added, :description, :last_version, :last_version_status, :last_test_status, :last_tested, :datum_1_name, :datum_1_type, :datum_2_name, :datum_2_type, :datum_3_name, :datum_3_type, :datum_4_name, :datum_4_type, :datum_5_name, :datum_5_type, :datum_6_name, :datum_6_type, :datum_7_name, :datum_7_type, :datum_8_name, :datum_8_type, :datum_9_name, :datum_9_type, :datum_10_name, :datum_10_type)
    end

    # get a bootstrap text class and an appropriate string to convert integer 
    # passing status to useful web output

    def passing_status_and_class(status)
      sts = 'ERROR'
      cls = 'text-info'
      if status == 0
        sts = 'Passing'
        cls = 'text-success'
      elsif status == 1
        sts = 'Failing'
        cls = 'text-danger'
      elsif status == 2
        sts = 'Mixed'
        cls = 'text-warning'
      elsif status == 3
        sts = 'Not yet run'
        cls = 'text-warning'
      end
      return sts, cls
    end
end

MESATestHub/app/helpers/test_cases_helper.rb
module TestCasesHelper
end

MESATestHub/app/views/test_cases/_form.html.haml
= bootstrap_form_for @test_case, inline_errors: false do |f|
  - if @test_case.errors.any?
    .form-row
      .col.alert.alert-danger
        %h4.alert-heading= "#{pluralize(@test_case.errors.count, "error")} prohibited this test case from being saved:"
        %p
          %ul
            - @test_case.errors.full_messages.each do |message|
              %li= message      
  .form-row
    .col.field
      = f.text_field :name, placeholder: 'wd2'
    .col.field
      = f.select :module, @modules.collect { |mod| [mod, mod] }, {include_blank: true}
    .col.field
      = f.number_field :version_added, placeholder: 10000
  .form-row
    .col.field
      = f.text_area :description, placeholder: 'description of what the test does'
      %small.form-text.text-muted What does the test do? Describe the physical situation at hand (i.e. an accreting white dwarf) and what constitutes "success" (i.e. it undergoes several flashes and then settles into stable burning).
  .form-row
    .col.field
      = f.text_field :datum_1_name, placeholder: 'name of additional data to be tracked'
    .col.field
      = f.select(:datum_1_type, options_for_select([['', nil], ['string', 'string'], ['float', 'float'], ['integer', 'integer'], ['boolean', 'boolean']]))
  .form-row
    .col.field
      = f.text_field :datum_2_name, placeholder: 'name of additional data to be tracked'
    .col.field
      = f.select(:datum_2_type, options_for_select([['', nil], ['string', 'string'], ['float', 'float'], ['integer', 'integer'], ['boolean', 'boolean']]))
  .form-row
    .col.field
      = f.text_field :datum_3_name, placeholder: 'name of additional data to be tracked'
    .col.field
      = f.select(:datum_3_type, options_for_select([['', nil], ['string', 'string'], ['float', 'float'], ['integer', 'integer'], ['boolean', 'boolean']]))
  .form-row
    .col.field
      = f.text_field :datum_4_name, placeholder: 'name of additional data to be tracked'
    .col.field
      = f.select(:datum_4_type, options_for_select([['', nil], ['string', 'string'], ['float', 'float'], ['integer', 'integer'], ['boolean', 'boolean']]))
  .form-row
    .col.field
      = f.text_field :datum_5_name, placeholder: 'name of additional data to be tracked'
    .col.field
      = f.select(:datum_5_type, options_for_select([['', nil], ['string', 'string'], ['float', 'float'], ['integer', 'integer'], ['boolean', 'boolean']]))
  .form-row
    .col.field
      = f.text_field :datum_6_name, placeholder: 'name of additional data to be tracked'
    .col.field
      = f.select(:datum_6_type, options_for_select([['', nil], ['string', 'string'], ['float', 'float'], ['integer', 'integer'], ['boolean', 'boolean']]))
  .form-row
    .col.field
      = f.text_field :datum_7_name, placeholder: 'name of additional data to be tracked'
    .col.field
      = f.select(:datum_7_type, options_for_select([['', nil], ['string', 'string'], ['float', 'float'], ['integer', 'integer'], ['boolean', 'boolean']]))
  .form-row
    .col.field
      = f.text_field :datum_8_name, placeholder: 'name of additional data to be tracked'
    .col.field
      = f.select(:datum_8_type, options_for_select([['', nil], ['string', 'string'], ['float', 'float'], ['integer', 'integer'], ['boolean', 'boolean']]))
  .form-row
    .col.field
      = f.text_field :datum_9_name, placeholder: 'name of additional data to be tracked'
    .col.field
      = f.select(:datum_9_type, options_for_select([['', nil], ['string', 'string'], ['float', 'float'], ['integer', 'integer'], ['boolean', 'boolean']]))
  .form-row
    .col.field
      = f.text_field :datum_10_name, placeholder: 'name of additional data to be tracked'
    .col.field
      = f.select(:datum_10_type, options_for_select([['', nil], ['string', 'string'], ['float', 'float'], ['integer', 'integer'], ['boolean', 'boolean']]))
  .form-row
    .col.text-center
      .actions
        .btn-group
          = link_to 'View All Test Cases', test_cases_path, class: 'btn btn-lg btn-secondary text-light'
          - if @show_path
            = link_to 'Show', @show_path, class: 'btn btn-lg btn-secondary text-light'
          = f.submit 'Save', {class: "btn btn-lg btn-primary"}

MESATestHub/app/views/test_cases/edit.html.haml
%h1
  Editing
  %samp=@test_case.name

= render 'form'

MESATestHub/app/views/test_cases/index.html.haml
.row.text-center
  .col
    %h1= @header_text
    %h3{class: @status_class}= @status_text
.row
  .col-lg-4.col-md-5.col-xs-12
    %h4 Computers Tested:
    %ul
      - @specs.each do |spec, comps|
        %li= "#{spec}: #{comps.join(', ')}"
  .col-lg-8.col-md-7.col-xs-12
    %form{action: test_cases_path, method: 'get', class: 'form-inline'}
      .col-auto.col-form-label.align-middle
        =label_tag "version", 'MESA version: ', class: 'control-label form-control-lg'
      .col-auto.align-middle
        =select_tag "version", options_for_select(@mesa_versions, @selected), class: 'custom-select form-control form-control-lg'
      .col-auto.align-middle
        =submit_tag 'Go', class: 'btn btn-primary text-light form-control', name: nil



.row#index-desc
  .col
    .card-deck
      .card.border-success
        .card-body.text-success
          %h4.card-title Passing
          %p.card-text
            %b=@statistics[:passing]
            tests where all computers report passing.
      .card.border-warning
        .card-body.text-warning
          %h3.card-title Mixed
          %p.card-text
            %b=@statistics[:mixed]
            tests where some computers report passing and others report failing.
      .card.border-danger
        .card-body.text-danger
          %h3.card-title Failing
          %p.card-text
            %b=@statistics[:failing]
            tests where all computers report failing.

.row
  .col
    %table.table.table-hover.table-responsive#test_summary
      %thead.thead-default
        %tr
          %th Name
          - if @selected == 'all'
            %th Last Version Tested
          - else
            %th Computers Tested
          %th Last Tested Date

      %tbody
        - @test_cases.each do |test_case|
          %tr{class: @row_classes[test_case] + ' clickable-row', "data-href":test_case_path(test_case, version: @selected), id: test_case.name + '-row'}
            %td
              %samp= test_case.name
            - if @selected == 'all'
              %td= @last_versions[test_case]
            - else
              %td= @computer_counts[test_case]
            %td= @last_tested[test_case]
.row
  .col.text-center
    - if admin?
      =link_to "Create Test Case", new_test_case_path, class: 'btn btn-lg btn-primary text-light'

MESATestHub/app/views/test_cases/new.html.haml
.row
  .col
    %h1 New Test Case

= render 'form'

MESATestHub/app/views/test_cases/show.html.haml
%p#notice= notice

.row
  .col-lg-6.col-xs12
    %h3
      %samp=@test_case.name + ':'
      %span{class: @version_class}=@version_status
    %form{action: test_case_path(@test_case), method: 'get', class: 'form-inline'}
      .row.align-items-center
        .col-auto.col-form-label.align-middle
          =label_tag "version", 'MESA version: ', class: 'control-label form-control-lg'
        .col-auto.align-middle
          =select_tag "version", options_for_select(@mesa_versions, @selected), class: 'custom-select form-control form-control-lg'
        .col-auto.align-middle
          =submit_tag 'Go', class: 'btn btn-primary text-light form-control', name: nil

    %table.table
      %tr
        %th{scope: 'row'} Module
        %td
          %samp=@test_case.module
      %tr
        %th{scope: 'row'} Description
        %td=@test_case.description
      %tr
        %th{scope: 'row'}
          %samp MESA
          Version
        %td=@version_number
      %tr
        %th{scope: 'row'} Values Tracked
        %td= @test_case.data_names.join(", ")
      %tr
        %th{scope: 'row'} Version Added
        %td= @test_case.version_added
    .text-center
      .btn-group{style: 'margin-bottom: 20px'}
        - if admin?
          = link_to 'Edit', edit_test_case_path(@test_case), class: 'btn btn-primary btn-md text-light'
        = link_to 'View All Cases', test_cases_path(version: @selected), class: 'btn btn-secondary btn-md text-light'
        - if admin?
          = link_to 'Delete', @test_case, method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-danger btn-md text-light'
  .col-lg-6.col-xs-12
    %h3
      All test instances for version
      =@version_number
    - if not @test_instances.empty?
      %table.table.table-hover.table-sm.table-responsive#test-detail
        %thead.thead-default
          %tr
            %th Date Uploaded
            %th Computer
            %th Runtime [s]
        %tbody
          - @test_instances.each do |instance|
            %tr{class: @test_instance_classes[instance] + " clickable-row", "data-href": test_case_test_instance_path(@test_case, instance)}
              %td=instance.created_at
              %td=instance.computer.name
              %td=instance.runtime_seconds
    - else
      .alert.alert-warning
        %h4 No tests have been run yet.
    .text-center
      .btn-group
        - if admin?
          = link_to 'Add Instance', new_test_case_test_instance_path(@test_case), class: 'btn btn-primary btn-md text-light'
        = link_to 'View All Instances', test_case_test_instances_path(@test_case), class: 'btn btn-secondary btn-md text-light'