MESATestHub/config/routes.rb
Rails.application.routes.draw do
  get 'sessions/new'

  resources :users do
    resources :computers
  end
  resources :sessions
  resources :computers
  resources :test_cases do
    resources :test_instances
  end

  root to: 'test_cases#index' # , params: { version: 'latest' }

  # meant for remote HTTP requests
  post '/test_instances/submit', to: 'test_instances#submit'

  get 'admin', to: 'users#admin', as: 'admin'
  get 'admin_edit_user', to: 'users#admin_edit_user', as: 'admin_edit_user'
  delete 'admin_destroy_user', to: 'users#admin_destroy_user',
                               as: 'admin_delete_user'

  get 'signup', to: 'users#new', as: 'signup'
  get 'login', to: 'sessions#new', as: 'login'
  get 'logout', to: 'sessions#destroy', as: 'logout'

  post 'check_user', to: 'sessions#check_credentials', as: 'check_user'
  post 'check_computer', to: 'computers#check_computer', as: 'check_computer'

  # index of a particular user's computers's test instances
  get 'user/:user_id/computers/:id/test_instances',
      to: 'computers#test_instances_index',
      as: 'user_computer_test_instances'

  # global list of all computers (admins only)
  get 'all_computers', to: 'computers#index_all', as: 'all_computers'
end

MESATestHub/app/models/user.rb
class User < ApplicationRecord
  has_many :computers
  has_many :test_instances, through: :computers

  validates_uniqueness_of :email
  validates_presence_of :name

  # do checks on password to make sure it is long enough when we change, but
  # doesn't complain when it is left blank and unchanged during an edit
  validates :password, presence: { on: create }, length: { minimum: 8 },
    :if => :password_digest_changed?

  # validates :password, length: { in: 6..32 }

  has_secure_password

  def admin?
    admin
  end
end

MESATestHub/app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: %i[show edit update destroy]
  before_action :authorize_user
  before_action :authorize_admin, only: %i[new create admin destroy
                                           admin_edit_user admin_destroy_user]
  before_action :authorize_self_or_admin, only: %i[edit update]

  def index
    @users = User.all.order(:name)
  end

  def new
    @user = User.new
  end

  def show
    @computers = @user.computers
    @test_instances = @user.test_instances.order(
      mesa_version: :desc, created_at: :desc
    ).limit(20)
    @test_instance_classes = {}
    @test_instances.each do |instance| 
      @test_instance_classes[instance] = instance.passed ? 'table-success' : 'table-danger'
    end
  end

  def create
    @user = User.new(user_params)
    if @user.save
      redirect_to users_path, notice: "Successfully set up #{@user.name}."
    else
      render "new"
    end
  end

  def update
    respond_to do |format|
      # set custom params hash to make sure admin doesn't get spoofed
      update_params = {}
      user_params.each { |key, value| update_params[key] = value }

      # only admins can upgrade users to admin status
      # update_params['admin'] ||= false unless current_user.admin?

      # do update
      if @user.update(update_params)
        format.html do
          redirect_to @user, notice: "#{@user.name} was successfully updated."
        end
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  def edit; end

  def destroy
    # prevent bricking of session if destroying self
    session[:user_id] = nil if @user.id == current_user.id
    @user.destroy
    respond_to do |format|
      format.html do 
        redirect_to users_url, notice: 'User was successfully destroyed.'
      end
      format.json { head :no_content }
    end
  end

  def admin
    # for selecting from all users
    @users = User.all.order(:name)

    # for building a new user
    @user = User.new

    # for building a new test case
    @test_case = TestCase.new

    # for making select field for a new test case
    @modules = TestCase.modules

    render 'admin'
  end

  def admin_edit_user
    user = User.find(admin_edit_user_params[:user_id])
    if user
      redirect_to edit_user_path(user)
    else
      redirect_to admin_path, alert: 'Invalid User'
    end
  end

  def admin_destroy_user
    user = User.find(admin_edit_user_params[:user_id])
    if user
      # prevent bricking of session if destroying self
      session[:user_id] = nil if user.id == current_user.id
      user.destroy
      redirect_to admin_path, notice: 'User was successfully destroyed.'
    else
      redirect_to admin_path, alert: 'Invalid User'
    end
  end

  private

  def set_user
    @user = User.find(params[:id])
  end

  def user_params
    params.require(:user).permit(:email, :password, :password_confirmation,
                                 :name, :admin)
  end

  def admin_edit_user_params
    params.permit(:user_id)
  end
end

MESATestHub/app/helpers/users_helper.rb
module UsersHelper
end

MESATestHub/app/views/users/admin.html.haml
.row
  .col
    %h1 Administrator Actions
    %p 
      %b
        Below are controls that are largely scattered throughout the web app
        that only administrators can access. They are assembled here for
        convenience.

.row
  .col
    %h2 Test Control
    %p
      Add, edit, or delete test cases.
.row
  .col
    %h4 Add New Test Case
    %hr

= bootstrap_form_for @test_case, inline_errors: false do |f|

  - if @test_case.errors.any?
    .form-row
      .col.alert.alert-danger
        %h4.alert-heading= "#{pluralize(@test_case.errors.count, "error")} prohibited this test case from being saved:"
        %p
          %ul
            - @test_case.errors.full_messages.each do |message|
              %li= message      
  .form-row
    .col.field
      = f.text_field :name, placeholder: 'wd2'
    .col.field
      = f.select :module, @modules.collect { |mod| [mod, mod] }, { include_blank: true}
    .col.field
      = f.number_field :version_added, placeholder: 10000
  .form-row
    .col.field
      = f.text_area :description, placeholder: 'description of what the test does'
      %small.form-text.text-muted What does the test do? Describe the physical situation at hand (i.e. an accreting white dwarf) and what constitutes "success" (i.e. it undergoes several flashes and then settles into stable burning).
  .form-row
    .col.field
      = f.text_field :datum_1_name, placeholder: 'name of additional data to be tracked'
    .col.field
      = f.select(:datum_1_type, options_for_select([['', nil], ['string', 'string'], ['float', 'float'], ['integer', 'integer'], ['boolean', 'boolean']]))
  .form-row
    .col.field
      = f.text_field :datum_2_name, placeholder: 'name of additional data to be tracked'
    .col.field
      = f.select(:datum_2_type, options_for_select([['', nil], ['string', 'string'], ['float', 'float'], ['integer', 'integer'], ['boolean', 'boolean']]))
  .form-row
    .col.field
      = f.text_field :datum_3_name, placeholder: 'name of additional data to be tracked'
    .col.field
      = f.select(:datum_3_type, options_for_select([['', nil], ['string', 'string'], ['float', 'float'], ['integer', 'integer'], ['boolean', 'boolean']]))
  .form-row
    .col.field
      = f.text_field :datum_4_name, placeholder: 'name of additional data to be tracked'
    .col.field
      = f.select(:datum_4_type, options_for_select([['', nil], ['string', 'string'], ['float', 'float'], ['integer', 'integer'], ['boolean', 'boolean']]))
  .form-row
    .col.field
      = f.text_field :datum_5_name, placeholder: 'name of additional data to be tracked'
    .col.field
      = f.select(:datum_5_type, options_for_select([['', nil], ['string', 'string'], ['float', 'float'], ['integer', 'integer'], ['boolean', 'boolean']]))
  .form-row
    .col.field
      = f.text_field :datum_6_name, placeholder: 'name of additional data to be tracked'
    .col.field
      = f.select(:datum_6_type, options_for_select([['', nil], ['string', 'string'], ['float', 'float'], ['integer', 'integer'], ['boolean', 'boolean']]))
  .form-row
    .col.field
      = f.text_field :datum_7_name, placeholder: 'name of additional data to be tracked'
    .col.field
      = f.select(:datum_7_type, options_for_select([['', nil], ['string', 'string'], ['float', 'float'], ['integer', 'integer'], ['boolean', 'boolean']]))
  .form-row
    .col.field
      = f.text_field :datum_8_name, placeholder: 'name of additional data to be tracked'
    .col.field
      = f.select(:datum_8_type, options_for_select([['', nil], ['string', 'string'], ['float', 'float'], ['integer', 'integer'], ['boolean', 'boolean']]))
  .form-row
    .col.field
      = f.text_field :datum_9_name, placeholder: 'name of additional data to be tracked'
    .col.field
      = f.select(:datum_9_type, options_for_select([['', nil], ['string', 'string'], ['float', 'float'], ['integer', 'integer'], ['boolean', 'boolean']]))
  .form-row
    .col.field
      = f.text_field :datum_10_name, placeholder: 'name of additional data to be tracked'
    .col.field
      = f.select(:datum_10_type, options_for_select([['', nil], ['string', 'string'], ['float', 'float'], ['integer', 'integer'], ['boolean', 'boolean']]))
  .actions
    = f.submit 'Save', {class: "btn btn-lg btn-primary"}
.row
  .col
    %hr
.row
  .col
    %h4 Edit/Delete Test cases (needs to be implemented)
    %hr

.row
  .col
    %h2 User Control
    %p Add, edit, or delete users
    %hr
.row
  .col
    %h4 Add new user
=bootstrap_form_for @user do |f|
  - if @user.errors.any?
    .form-row
      .col.alert.alert-danger
        %h4.alert-heading= "#{pluralize(@user.errors.count, "error")} prohibited this user from being saved:"
        %p
          %ul
            - @user.errors.full_messages.each do |message|
              %li= message      
  .form-row
    .col.field=f.text_field :email
  .form-row
    .col.field=f.password_field :password, label: "New Password"
    .col.field=f.password_field :password_confirmation, label: "Confirm New Password"
  .form-row
    .col.field=f.text_field :name
  - if current_user.admin?
    .form-row
      .col.field
        =f.form_group :admin do
          =f.check_box :admin
  .form-row
    .actions=f.submit 'Save', {class: 'btn btn-lg btn-primary'}
%hr

.row
  .col
    .h4 Edit User
=bootstrap_form_tag url: admin_edit_user_path, method: 'get' do |f|
  .form-row
    .col.field=f.select :user_id, @users.collect {|user| [user.name, user.id]}
  .form-row
    .actions=f.submit 'Edit', {class: 'btn btn-lg'}
%hr
.row
  .col
    %h4 Delete User
=bootstrap_form_tag url: admin_delete_user_path, method: 'delete' do |f|
  .form-row
    .col.field=f.select :user_id, @users.collect {|user| [user.name, user.id]}
  .form-row
    .actions=f.submit 'Delete', {class: 'btn btn-lg btn-danger', data: {confirm: "Are you absolutely sure you want to delete this user?\n\nAll of their computers and test data will be deleted, too."}}



      

MESATestHub/app/views/users/edit.html.haml
.row
  .col
    %h1
      Edit
      =@user.name

=bootstrap_form_for @user do |f|
  - if @user.errors.any?
    .form-row
      .col.alert.alert-danger
        %h4.alert-heading= "#{pluralize(@user.errors.count, "error")} prohibited this user from being saved:"
        %p
          %ul
            - @user.errors.full_messages.each do |message|
              %li= message      
  .form-row
    .col.field=f.text_field :email
  .form-row
    .col.field=f.password_field :password, label: "New Password"
    .col.field=f.password_field :password_confirmation, label: "Confirm New Password"
  .form-row
    .col.field=f.text_field :name
  - if current_user.admin?
    .form-row
      .col.field
        =f.form_group :admin, label: { text: "Is this person an admin?" } do
          =f.check_box :admin

  .form-row
    .actions=f.submit 'Save', {class: 'btn btn-lg btn-primary'}

MESATestHub/app/views/users/index.html.haml
.row
  .col
    %h1 All Users

.row
  .col
    %table.table.table-responsive#test_summary
      %thead.thead-default
        %tr
          %th Name
          %th Email
          %th Computers
          %th

      %tbody
        - @users.each do |user|
          %tr
            %td.align-middle= user.name
            %td.align-middle= user.email
            %td.align-middle 
              -user.computers.each do |c| 
                -if c == user.computers[-1]
                  =link_to c.name, user_computer_path(user, c)
                -else
                  =link_to(c.name, user_computer_path(user, c)) + ', '
            %td.align-middle
              = link_to 'Show', user_path(user), class: 'btn btn-sm btn-secondary text-light'
              - if current_user.admin?
                = link_to 'Edit', edit_user_path(user), class: 'btn btn-sm btn-primary text-light'
                = link_to 'Delete', user_path(user), method: :delete, data: {confirm: "Are you absolutely sure you want to delete this user?\n\nAll of their computers and test data will be deleted, too."}, class: 'btn btn-sm btn-danger text-light'
- if admin?
  .row
    .col.text-center
      %a{href: new_user_path}
        %button.btn.btn-primary.btn-lg Create User

MESATestHub/app/views/users/new.html.haml
.row
  .col
    %h1 New User

=bootstrap_form_for @user do |f|
  - if @user.errors.any?
    .form-row
      .col.alert.alert-danger
        %h4.alert-heading= "#{pluralize(@user.errors.count, "error")} prohibited this test case from being saved:"
        %p
          %ul
            - @user.errors.full_messages.each do |message|
              %li= message      
  .form-row
    .col.field=f.text_field :email, placeholder: 'paxton@kitp.ucsb.edu'
  .form-row
    .col.field=f.password_field :password
    .col.field=f.password_field :password_confirmation
  .form-row
    .col.field=f.text_field :name
  .form-row
    .col.field
      =f.form_group :admin, label: { text: "Is this person an admin?" } do
        =f.check_box :admin do
          Check this to make the user an admin. Admins can add or remove test
          cases and users. They can edit test results of any user (not just
          their own). A non-admin can submit tests and edit their own results.
  .form-row
    .actions=f.submit 'Save', {class: 'btn btn-lg btn-primary'}

MESATestHub/app/views/users/show.html.haml
.row
  .col
    %p#notice= notice
.row
  .col-lg-6.col-xs-12
    %h3= "#{@user.name} Details"
    %table.table
      %tr
        %th{scope: 'row'} Name
        %td= @user.name
      %tr
        %th{scope: 'row'} Email
        %td= @user.email
      %tr
        %th{scope: 'row'} Admin
        %td= @user.admin ? 'Yes' : 'No'
    .text-center
      .btn-group
        = link_to 'All Users', users_path, class: 'btn btn-md btn-secondary text-light'
        - if self_or_admin?
          = link_to 'Edit', edit_user_path(@user), class: 'btn btn-md btn-primary text-light'
        - if admin?
          = link_to 'Delete', user_path(@user), method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-md btn-danger text-light'
    - unless @user.computers.empty?
      %hr
      %h3= "#{@user.name}'s Computers"
      %table.table
        %thead.thead-default
          %tr
            %th Name
            %th Actions
        %tbody
          - @computers.each do |computer|
            %tr
              %td.align-middle= computer.name
              %td.align-middle
                .btn-group
                  =link_to 'Show', user_computer_path(@user, computer), class: 'btn btn-sm btn-secondary text-light'
                  - if self_or_admin?
                    =link_to 'Edit', edit_user_computer_path(@user, computer), class: 'btn btn-sm btn-primary text-light'
                    =link_to 'Delete', user_computer_path(@user, computer), method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-sm btn-danger text-light'
      .text-center= link_to "More Computer Info", user_computers_path(@user), class: 'btn btn-md btn-secondary text-light'
      %hr
  .col-lg-6.col-xs-12
    - if @test_instances.empty?
      .alert.alert-warning.align-middle
        %h4= "#{@user.name} has not yet run any tests"
    - else
      %h3= "Latest results from #{@user.name}"
      %table.table.table-hover.table-sm.table-responsive
        %thead.thead-default
          %tr
            %th Version
            %th Date Uploaded
            %th Test Case
            %th Computer
          %tbody
            - @test_instances.each do |instance|
              %tr{class: @test_instance_classes[instance] + ' clickable-row', 'data-href': test_case_test_instance_path(instance.test_case, instance)}
                %td=instance.mesa_version
                %td=instance.created_at.utc.strftime "%Y-%m-%d"
                %td
                  %samp=instance.test_case.name
                %td=instance.computer.name
    -# .text-center
    -#   = link_to "All tests from #{@user.name}", user_test_instances_path(@user), class: 'btn btn-lg btn-secondary text-light'