MESATestHub/config/routes.rb
Rails.application.routes.draw do
  get 'sessions/new'

  resources :users do
    resources :computers
  end
  resources :sessions
  resources :computers
  resources :test_cases do
    resources :test_instances
  end

  root to: 'test_cases#index' # , params: { version: 'latest' }

  # meant for remote HTTP requests
  post '/test_instances/submit', to: 'test_instances#submit'

  get 'admin', to: 'users#admin', as: 'admin'
  get 'admin_edit_user', to: 'users#admin_edit_user', as: 'admin_edit_user'
  delete 'admin_destroy_user', to: 'users#admin_destroy_user',
                               as: 'admin_delete_user'

  get 'signup', to: 'users#new', as: 'signup'
  get 'login', to: 'sessions#new', as: 'login'
  get 'logout', to: 'sessions#destroy', as: 'logout'

  post 'check_user', to: 'sessions#check_credentials', as: 'check_user'
  post 'check_computer', to: 'computers#check_computer', as: 'check_computer'

  # index of a particular user's computers's test instances
  get 'user/:user_id/computers/:id/test_instances',
      to: 'computers#test_instances_index',
      as: 'user_computer_test_instances'

  # global list of all computers (admins only)
  get 'all_computers', to: 'computers#index_all', as: 'all_computers'
end

MESATestHub/app/models/computer.rb
class Computer < ApplicationRecord
  has_many :test_data, through: :test_instances
  has_many :test_instances, dependent: :destroy
  belongs_to :user
  validates_presence_of :name
  validates_uniqueness_of :name
  validates_presence_of :user_id
  validates_presence_of :platform

  def self.platforms
    %w[macOS linux]
  end

  validates_inclusion_of :platform, in: %w[macOS linux]

  def user_name
    user.name
  end

  def email
    user.email
  end

  def validate_user(creator)
    return if creator.admin? || (creator.id == user_id)
    errors.add(:user, 'must be current user unless you are an admin.')
  end
end

MESATestHub/app/controllers/computers_controller.rb
class ComputersController < ApplicationController
  before_action :set_user, only: %i[show new create index edit update destroy
                                    test_instances_index]
  before_action :set_computer, only: %i[show edit update destroy
                                        test_instances_index]
  before_action :authorize_self_or_admin, only: %i[new create edit update
                                                   destroy]
  before_action :authorize_admin, only: %i[index_all]

  skip_before_action :verify_authenticity_token, only: [:check_computer]

  # GET /computers
  # GET /computers.json
  def index
    @owner_prefix = "#{@user.name}'s"
    @computers = @user.computers
  end

  def index_all
    @owner_prefix = 'All'
    @show_users = true
    @computers = Computer.all.includes(:user)
    # @computers.sort_by { |c| c.user.name }
    render 'index'
  end

  # GET /computers/1/test_instances
  # GET /computers/1/test_instances.json
  def test_instances_index
    @computer_instances = @computer.test_instances.order(mesa_version: :desc)
  end

  # GET /computers/1
  # GET /computers/1.json
  def show
    @test_instances = @computer.test_instances.order(
      mesa_version: :desc, created_at: :desc
    ).limit(20)
    @test_instance_classes = {}
    @test_instances.each do |instance|
      @test_instance_classes[instance] =
        if instance.passed
          'table-success'
        else
          'table-danger'
        end
    end
  end

  # GET /computers/new
  def new
    @computer = @user.computers.build
  end

  # GET /computers/1/edit
  def edit
    @show_path = user_computer_path(@user, @computer)
  end

  # POST /computers
  # POST /computers.json
  def create
    @computer = Computer.new(computer_params)
    user = User.find(params[:computer][:user_id])
    unless admin? || (user && current_user && user.id == current_user.id)
      @computer.errors.add(:user_id, 'must be ' \
        'yourself unless you are an admin.')
    end

    # this if clause shouldn't be necessary, but I can't get it to work
    # otherwise
    if @computer.errors.any?
      render 'new'
    else
      respond_to do |format|
        if @computer.save
          format.html do
            redirect_to [@computer.user, @computer],
                        notice: 'Computer was successfully created.'
          end
          format.json { render :show, status: :created, location: @computer }
        else
          format.html { render :new }
          format.json do
            render json: @computer.errors, status: :unprocessable_entity
          end
        end
      end
    end
  end

  # PATCH/PUT /computers/1
  # PATCH/PUT /computers/1.json
  def update
    respond_to do |format|
      if params[:computer][:user_id]
        # only allow setting the computer's user to the logged in user unless
        # it's an admin. Skip the process if a user_id wasn't specified.
        user = User.find(params[:computer][:user_id])
        unless admin? || (user && current_user && user.id == current_user.id)
          @computer.errors.add(:user_id, 'must be yourself unless you are ' \
                                         'an admin.')
        end
      end

      if @computer.update(computer_params)
        format.html do
          redirect_to user_computer_path(computer_params[:user_id], @computer),
                      notice: 'Computer was successfully updated.'
        end
        format.json { render :show, status: :ok, location: @computer }
      else
        format.html { render :edit }
        format.json do
          render json: @computer.errors, status: :unprocessable_entity
        end
      end
    end
  end

  # DELETE /computers/1
  # DELETE /computers/1.json
  def destroy
    @computer.destroy
    respond_to do |format|
      format.html do
        redirect_to user_computers_url(@user),
                    notice: 'Computer was successfully destroyed.'
      end
      format.json { head :no_content }
    end
  end

  # POST /check_computer.json
  # pretty dumb for html, but it should work, I guess
  def check_computer
    user = User.find_by(email: check_computer_params[:email])
    if user && user.authenticate(check_computer_params[:password])
      if user.computers.find_by(name: check_computer_params[:computer_name])
        # authenticated and computer belongs to user. Proceed!
        respond_to do |format|
          format.html do
            session[:user_id] = user.id
            redirect_to user_computers_path(user)
          end
          format.json do
            # send back the all clear
            render json: {
              valid: true,
              message: 'Email, password, and computer name accepted'
            }
          end
        end
      else
        # authenticated, but computer matching fails
        respond_to do |format|
          format.html do
            session[:user_id] = user.id
            redirect_to user_computers_path(user),
                        alert: "#{params[:computer_name]} is not one of your " \
                               'computers.'
          end
          format.json do
            render json: {
              valid: false,
              message: 'Email and password are valid, but submitted computer '\
                'name does not match any computer on MESATestHub. Set it up '\
                'there first before submitting.'
            }
          end
        end
      end
    else
      # we are NOT authenticated
      respond_to do |format|
        format.html do
          flash.error = "Email or password is invalid"
          redirect_to login_path
        end
        format.json do
          render json: { valid: false, message: "Email or password are wrong."}
        end
      end
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_computer
    @computer = @user.computers.find(params[:id])
  end

  def set_user
    @user = User.find(params[:user_id])
  end

  # Never trust parameters from the scary internet, only allow the white list
  # through.
  def computer_params
    params.require(:computer).permit(:name, :user_id, :platform, :processor,
                                     :ram_gb)
  end

  def check_computer_params
    params.permit(:email, :password, :computer_name)
  end

  def authorize_self_or_admin
    return if admin? || @user.id == current_user.id
    redirect_to login_url, alert: 'Must be an admin or the user in ' \
      'question to do that action.'
  end
end

MESATestHub/app/helpers/computers_helper.rb
module ComputersHelper
end

MESATestHub/app/views/computers/_form.html.haml
= bootstrap_form_for [@user, @computer] do |f|
  - if @computer.errors.any?  
    .form-row
      .col.alert.alert-danger
        %h4.alert-heading= "#{pluralize(@computer.errors.count, "error")} prohibited this test instance from being saved:"
        %p
          %ul
            - @computer.errors.full_messages.each do |message|
              %li= message
  .form-row
    .col.field
      = f.text_field :name, placeholder: "Compy 5000"
    .col.field
      = f.select :user_id, User.all.order(:name).collect { |user| [user.name, user.id] }, selected: @user.id
      -# = f.text_field :user, placeholder: "Bill Paxton"
  .form-row
    .col.field
      = f.select :platform, options_for_select(Computer.platforms, Computer.platforms)
    .col.field
      = f.text_field :processor, placeholder: "2.7 GHz 12-Core Intel Xeon E5"
    .col.field
      = f.number_field :ram_gb, placeholder: 16
  .form-row.text-center
    .col.actions
      .btn-group
        = link_to 'View My Computers', user_computers_path(@user), class: 'btn btn-secondary btn-lg text-light'
        - if @show_path
          = link_to 'Show', @show_path, class: 'btn btn-secondary btn-lg text-light'
        = f.submit 'Save', class: 'btn btn-primary btn-lg'

MESATestHub/app/views/computers/edit.html.haml
%h1 Editing computer

= render 'form'

MESATestHub/app/views/computers/index.html.haml
.row
  .col
    %h1 
      = @owner_prefix
      Computers

.row
  .col
    %table.table.table-responsive
      %thead.thead-default
        %tr
          %th Name
          - if @show_users
            %th User
          %th Platform
          %th Processor
          %th Ram [GB]
          %th
          -if self_or_admin?
            %th
            %th

      %tbody
        - @computers.each do |computer|
          %tr
            %td.align-middle= computer.name
            - if @show_users
              %td= link_to computer.user.name, user_computer_path(computer.user, computer)
            %td.align-middle.align-middle= computer.platform
            %td.align-middle= computer.processor
            %td.align-middle= computer.ram_gb
            %td.align-middle= link_to 'Show', user_computer_path(computer.user, computer), class: 'btn btn-sm btn-secondary text-light'
            - if self_or_admin?
              %td.align-middle= link_to 'Edit', edit_user_computer_path(computer.user, computer), class: 'btn btn-sm btn-primary text-light'
              %td.align-middle= link_to 'Delete', user_computer_path(computer.user, computer), method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-sm btn-danger text-light'

- if @user
  .row
    .col.text-center
      .btn-group
        - if self_or_admin?
          = link_to 'New Computer', new_user_computer_path(@user), class: 'btn btn-primary btn-lg text-light'
        = link_to 'View User', user_path(@user), class: 'btn btn-secondary btn-lg text-light'

MESATestHub/app/views/computers/new.html.haml
%h1 New computer

= render 'form'

MESATestHub/app/views/computers/show.html.haml
.row
  .col
    %p#notice= notice

.row
  .col-lg-6.col-xs-12
    %h3="#{@computer.name} details"
    %table.table
      %tr
        %th{scope: 'row'} User
        %td= link_to @user.name, user_path(@user)
      %tr
        %th{scope: 'row'} Platform
        %td=@computer.platform
      %tr
        %th{scope: 'row'} Processor
        %td=@computer.processor
      %tr
        %th{scope: 'row'} RAM
        %td=@computer.ram_gb.to_s + ' GB'
    %br
    .text-center
      .btn-group
        - if self_or_admin?
          = link_to 'Edit', edit_user_computer_path(@user, @computer), class: 'btn btn-md btn-primary text-light'
        = link_to "View #{self? ? 'My' : @user.name + "'s"} Computers", user_computers_path(@user), class: 'btn btn-md btn-secondary text-light'
        - if self_or_admin?
          = link_to 'Delete', [@user, @computer], method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-danger btn-md text-light'
  .col-lg-6.col-xs-12
    - if @test_instances.empty?
      .alert.alert-warning.align-middle
        %h4 No tests have been run yet
    - else
      %h3= "Latest results from #{@computer.name}"
      %table.table.table-hover.table-sm.table-responsive#computer-detail
        %thead.thead-default
          %tr
            %th Date Uploaded
            %th Test Case
            %th Runtime [s]
          %tbody
            - @test_instances.each do |instance|
              %tr{class: @test_instance_classes[instance] + ' clickable-row', 'data-href': test_case_test_instance_path(instance.test_case, instance)}
                %td=instance.created_at.utc.strftime "%Y-%m-%d"
                %td=instance.test_case.name
                %td=instance.runtime_seconds 
      .text-center
        = link_to "All tests from #{@computer.name}", user_computer_test_instances_path(@user, @computer), class: 'btn btn-md btn-secondary text-light'

MESATestHub/app/views/computers/test_instances_index.html.haml
.row
  .col
    %h1 
      Test instances run by
      =@computer.name
.row
  .col
    %table.table.table-sm.table-responsive
      %thead.thead-default
        %tr
          %th Version
          %th Test Case
          %th Created
          %th Runtime
          %th Threads
          %th Compiler
          %th Platform
          %th Status
          %th
          - if admin?
            %th
            %th

      %tbody
        - @computer_instances.each do |test_instance|
          %tr
            %td.align-middle= test_instance.mesa_version
            %td.align-middle
              %samp= link_to test_instance.test_case.name, test_instance.test_case            
            %td.align-middle= test_instance.created_at.utc.strftime "%Y-%m-%d"
            %td.align-middle
              = test_instance.runtime_seconds
              s
            %td.align-middle= test_instance.omp_num_threads
            %td.align-middle= ((test_instance.compiler || '') + ' ' + (test_instance.compiler_version || '')).strip
            %td.align-middle= ((test_instance.computer.platform || '' ) + ' ' + (test_instance.platform_version || '')).strip
            %td.align-middle
              -if test_instance.passed
                %span.text-success= test_instance.passage_status
              -else
                %span.text-danger= test_instance.passage_status
            %td.align-middle= link_to 'Show', [ test_instance.test_case, test_instance], class: 'btn btn-sm btn-secondary text-light'
            -if admin?
              %td.align-middle= link_to 'Edit', edit_test_case_test_instance_path(test_instance.test_case, test_instance), class: 'btn btn-sm btn-primary text-light'
              %td.align-middle= link_to 'Destroy', [test_instance.test_case, test_instance], method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-sm btn-danger text-light'

.row
  .col.text-center
    .btn-group
      = link_to 'Computer Overview', user_computer_path(@user, @computer), class: 'btn btn-secondary btn-lg text-light'